### ISSUE TITLE
Features page

### ISSUE THREAD

**Issue by borseno** [RedDuck-Software/Badaboom#5]
# Text

Badaboom provides hardly-accessible blockchain information in an instant time. It was developed for developers, to retrieve various information that might help them to test/debug Ethereum and BSC transactions.

Very often, developers want to monitor state of a contract. They would like to see all the changes of their contract's state and get notifications when something changes. A typical scenario is getting a transaction that altered a field to a specific value in the past. Or getting the transactions that called a function with a specific value to know how the function behaves in such a case.

Currently, Badaboom supports advanced transaction filters, which include filters by:
- "From", "to" addresses
- Block number
- Contract address and function called
- Contract address and function called, with specific argument values provided **(Paid feature)**

<Button - try it out!>

We will soon introduce the following functionality:
- Filters by contract state that was altered in the transaction (checklist)
   - Fields for verified contracts
   - Storage for unverified contracts
- Contract page with a graphical sequence of state alterations that took place on a contract:
   - Fields altered for contracts with verified ABI on etherscan
   - Storage alterations for those without ABI on etherscan
 - Ability to verify previously unverified contract and restart indexing for it
 - Notifications
 
 # Layout
 
 ## Text
 ### Pricing widget
 ### Explorer widget

**Comment by lordannm** [comment]
Badaboom https://www.figma.com/file/C4m0PSODEMjVNy0P757qqp/Badaboom?node-id=0%3A1

eFund https://www.figma.com/file/2ioxtiFxAe0ZCPRMGdfo6k/e-Fund?node-id=0%3A1
